### ISSUE TITLE
[Tracking Issue] Checklist of features for MVP

### ISSUE THREAD

**Issue by sharnoff** [sharnoff/viri#3]
This issue serves to collect all of the features (that I've deemed are) required for a minimum viable product that are planned but *currently unimplemented*

There are a few broad categories here, some containing items that are more complex than others.

### Large(r) features
- [ ] search
  - [ ] -and replace
- [ ] Visual mode
  - [ ] visual line mode
  - [ ] **[Future]** visual block mode
- [ ] folds
- [ ] auto-indenting at the correct level
- [ ] auto-line break
- [ ] mapping - e.g. `nmap <C+j> <C-e>j`
- [ ] mark files as saved after undoing to most recent save
- [ ] highlight matching delimeters
- [ ] marks and nice jumping with double-backtick
- [ ] **[Future]** split edit history between open views
- [ ] **[Future]** vim-style macros
- [ ] **[Future]** multi-cursor normal/visual mode

### Keybindings
This is the biggest category - some of these are much more complex than others.
- [ ] `_` to start at first non-whitespace
- [x] `A` for `$a`
- [x] `B` as distinct from `b`
- [ ] Up/down arrow in colon mode to view history
- [x] `%` to jump to matching delimeter
- [ ] `di(` (or other delimeters) to delete within a delimeter
- [ ] resizing/moving splits
- [ ] `J` to collapse two lines
- [x] `f` and `;` to move to exact characters
- [x] `{n}G` and `gg`
- [x] `M` to move to the center of the screen
  - [x] With `H` and `L` to go to the top+bottom lines
- [ ] dot command (with separate undo modes - nvi/vim)

**Comment by sharnoff** [comment]
Closing because this version of the editor has not been in active development for a long time.
